version: '3'

services:

  app:
    build:
      context: .
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node-network
    tty: true
    command: node index.js
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
   build:
     context: ./nginx
     dockerfile: Dockerfile
   container_name: nginx
   networks:
     - node-network
   ports:
      - "8080:80"
   depends_on:
      - app

  db:
    image: arm64v8/mysql:oracle
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PORT=3306
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
